/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.awt.Label;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.DefaultCellEditor;
import javax.swing.table.DefaultTableModel;
import service.DBConnect;

/**
 *
 * @author Shakith
 */
public class add_notAvailable_groups extends javax.swing.JPanel {

    Generator generator;

    int id;

    /**
     * Creates new form add_notAvailable_groups
     */
    public add_notAvailable_groups() {
        initComponents();
        loadCombo();
        loadId();
        jTable2.setTableHeader(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        notAvailable_groups = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        notAvailable_groups.setBackground(new java.awt.Color(102, 51, 109));

        jPanel40.setBackground(new java.awt.Color(135, 19, 135));
        jPanel40.setPreferredSize(new java.awt.Dimension(1592, 109));

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-50.png"))); // NOI18N
        jLabel114.setToolTipText("");
        jLabel114.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel114MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel114MouseEntered(evt);
            }
        });

        jLabel115.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Add Not Available Times - Groups");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel114)
                .addGap(461, 461, 461)
                .addComponent(jLabel115)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel114))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(137, 14, 137));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Day");
        jPanel22.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Group");
        jPanel22.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox1.setOpaque(false);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel22.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 340, 36));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("To");
        jPanel22.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("From");
        jPanel22.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBox3));
        }

        jPanel22.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 540, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-30.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, -1, -1));

        jButton11.setText("Save");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 99, 41));

        javax.swing.GroupLayout notAvailable_groupsLayout = new javax.swing.GroupLayout(notAvailable_groups);
        notAvailable_groups.setLayout(notAvailable_groupsLayout);
        notAvailable_groupsLayout.setHorizontalGroup(
            notAvailable_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notAvailable_groupsLayout.createSequentialGroup()
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notAvailable_groupsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
        );
        notAvailable_groupsLayout.setVerticalGroup(
            notAvailable_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notAvailable_groupsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(868, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(notAvailable_groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(notAvailable_groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel114MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel114MouseClicked
        // TODO add your handling code here:
        generator.Parent.removeAll();
        generator.Parent.add(new notAvailable_groups());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jLabel114MouseClicked

    private void jLabel114MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel114MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel114MouseEntered

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        if ("Select...".equals(jComboBox1.getItemAt(0))) {
            jComboBox1.removeItemAt(0);
        }
        if ("Select...".equals(jComboBox1.getItemAt(jComboBox1.getItemCount() - 1))) {
            jComboBox1.removeItemAt(jComboBox1.getItemCount() - 1);
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{"", "", ""});
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        try {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                DBConnect.iud("INSERT INTO notavailable_groups VALUES('" + id + "','" + jComboBox1.getSelectedItem().toString() + "','" + model.getValueAt(i, 0) + "','" + model.getValueAt(i, 1) + "','" + model.getValueAt(i, 2) + "')");
                id++;
            }
            JOptionPane pane = new JOptionPane(new Label("Details added successfully"), JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = pane.createDialog("Data Saved");
            dialog.setModal(true);
            dialog.setVisible(true);

            //JOptionPane.showMessageDialog(this, "Data Saved", "Details added successfully", JOptionPane.INFORMATION_MESSAGE);
            generator.Parent.removeAll();
            generator.Parent.add(new notAvailable_groups());
            generator.Parent.repaint();
            generator.Parent.revalidate();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane pane = new JOptionPane(new Label("Details not added successfully"), JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = pane.createDialog("Data Not Saved");
            dialog.setModal(true);
            dialog.setVisible(true);

            //JOptionPane.showMessageDialog(this, "Data Not Saved", "Details Not successfully", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel notAvailable_groups;
    // End of variables declaration//GEN-END:variables

    public void loadCombo() {
        try {
            String qry = "SELECT * FROM groups";
            ResultSet rs = DBConnect.search(qry);
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Select...");
            while (rs.next()) {
                String batch = rs.getString("batch");
                String group = rs.getString("groups");

                int group_int = Integer.parseInt(group);
                for (int i = 1; i <= group_int; i++) {
                    jComboBox1.addItem(batch.concat(".0").concat(String.valueOf(i)));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadId() {
        try {
            String qry = "SELECT COUNT(notavailable_groups.id) as count FROM notavailable_groups";
            ResultSet rs = DBConnect.search(qry);
            rs.next();
            if (rs.getInt("count") == 0) {
                id = id + 1;
            } else {
                int i = rs.getInt("count");
                i++;
                id = id + i;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
