/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.awt.Label;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import service.DBConnect;
import static timetable.Generator.Parent;

/**
 *
 * @author Shakith
 */
public class edit_consecutive_sessions extends javax.swing.JPanel {

    public String num, session_1, session_2, session_3;

    Generator generator;

    /**
     * Creates new form edit_consecutive_sessions
     */
    public edit_consecutive_sessions() {
        initComponents();
    }

    public edit_consecutive_sessions(String num) {
        initComponents();

        this.num = num;

        setDetails();

        if (session_1.equals("N/A")) {
            jLabel43.setVisible(false);
            jLabel45.setVisible(false);
            jLabel41.setVisible(false);
            jComboBox3.setVisible(false);
            jComboBox4.setVisible(false);
            jComboBox1.setVisible(false);
        }
        if (session_2.equals("N/A")) {
            jLabel45.setVisible(false);
            jLabel41.setVisible(false);
            jComboBox4.setVisible(false);
            jComboBox1.setVisible(false);
        }
        if (session_3.equals("N/A")) {
            jLabel41.setVisible(false);
            jComboBox1.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit_consecutive_sessions = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        edit_consecutive_sessions.setBackground(new java.awt.Color(102, 51, 109));

        jPanel40.setBackground(new java.awt.Color(135, 19, 135));
        jPanel40.setPreferredSize(new java.awt.Dimension(1592, 109));

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-50.png"))); // NOI18N
        jLabel114.setToolTipText("");
        jLabel114.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel114MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel114MouseEntered(evt);
            }
        });

        jLabel115.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Edit Consecutive Sessions");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel114)
                .addGap(448, 448, 448)
                .addComponent(jLabel115)
                .addContainerGap(653, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel114))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(137, 14, 137));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox2.setOpaque(false);
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox2PropertyChange(evt);
            }
        });
        jPanel22.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 340, 36));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Session 1");
        jPanel22.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox3.setOpaque(false);
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel22.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 340, 36));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Group");
        jPanel22.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Session 3");
        jPanel22.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel22.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 340, 36));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Session 2");
        jPanel22.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        jComboBox4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox4PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel22.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 340, 36));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 100, 40));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 100, 40));

        javax.swing.GroupLayout edit_consecutive_sessionsLayout = new javax.swing.GroupLayout(edit_consecutive_sessions);
        edit_consecutive_sessions.setLayout(edit_consecutive_sessionsLayout);
        edit_consecutive_sessionsLayout.setHorizontalGroup(
            edit_consecutive_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_consecutive_sessionsLayout.createSequentialGroup()
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
            .addGroup(edit_consecutive_sessionsLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        edit_consecutive_sessionsLayout.setVerticalGroup(
            edit_consecutive_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_consecutive_sessionsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(569, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(edit_consecutive_sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(edit_consecutive_sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel114MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel114MouseClicked
        // TODO add your handling code here:
        generator.Parent.removeAll();
        generator.Parent.add(new consecutive_sessions());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jLabel114MouseClicked

    private void jLabel114MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel114MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel114MouseEntered

    private void jComboBox2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeVisible

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox2PropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2PropertyChange

    private void jComboBox3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeVisible

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox4PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4PopupMenuWillBecomeVisible

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            String qry = "DELETE FROM consecutive_sessions WHERE consecutive_sessions.id = '" + num + "' ";
            DBConnect.iud(qry);
            int des = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (des == 0) {
                JOptionPane.showMessageDialog(this, "Deleted Record", "Deleted Successfully", JOptionPane.INFORMATION_MESSAGE);
                generator.Parent.removeAll();
                generator.Parent.add(new consecutive_sessions());
                generator.Parent.repaint();
                generator.Parent.revalidate();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Deleting !!!", "Eror While Deleting", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            if (jComboBox4.getSelectedItem().toString().equals("N/A") && jComboBox1.getSelectedItem().toString().equals("N/A")) {
                String qry = "UPDATE consecutive_sessions SET consecutive_sessions.group ='" + jComboBox2.getSelectedItem().toString() + "' , consecutive_sessions.session_1 = '" + jComboBox3.getSelectedItem().toString() + "',consecutive_sessions.session_2 = '" + "N/A" + "',consecutive_sessions.session_3='" + "N/A" + "' WHERE id = '" + num + "'";
                DBConnect.iud(qry);
            } else if (jComboBox1.getSelectedItem().toString().equals("Select...")) {
                String qry = "UPDATE consecutive_sessions SET consecutive_sessions.group ='" + jComboBox2.getSelectedItem().toString() + "' , consecutive_sessions.session_1 = '" + jComboBox3.getSelectedItem().toString() + "',consecutive_sessions.session_2 = '" + jComboBox4.getSelectedItem().toString() + "',consecutive_sessions.session_3='" + "N/A" + "' WHERE id = '" + num + "'";
                DBConnect.iud(qry);
            } else {
                String qry = "UPDATE consecutive_sessions SET consecutive_sessions.group ='" + jComboBox2.getSelectedItem().toString() + "' , consecutive_sessions.session_1 = '" + jComboBox3.getSelectedItem().toString() + "',consecutive_sessions.session_2 = '" + jComboBox4.getSelectedItem().toString() + "',consecutive_sessions.session_3='" + jComboBox1.getSelectedItem().toString() + "' WHERE id = '" + num + "'";
                DBConnect.iud(qry);
            }

            JOptionPane pane = new JOptionPane(new Label("Details updated successfully"), JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = pane.createDialog("Data Updated");
            dialog.setModal(true);
            dialog.setVisible(true);

            //JOptionPane.showMessageDialog(this, "Data Saved", "Details added successfully", JOptionPane.INFORMATION_MESSAGE);
            generator.Parent.removeAll();
            generator.Parent.add(new consecutive_sessions());
            generator.Parent.repaint();
            generator.Parent.revalidate();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane pane = new JOptionPane(new Label("Details not updated successfully"), JOptionPane.ERROR_MESSAGE);
            JDialog dialog = pane.createDialog("Data Not updated");
            dialog.setModal(true);
            dialog.setVisible(true);

            //JOptionPane.showMessageDialog(this, "Data Not Saved", "Details Not successfully", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel edit_consecutive_sessions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel40;
    // End of variables declaration//GEN-END:variables

    public void setDetails() {
        try {
            String qry = "SELECT * FROM consecutive_sessions WHERE id='" + num + "'";
            ResultSet rs = DBConnect.search(qry);
            rs.first();

            session_1 = rs.getString("session_1");
            session_2 = rs.getString("session_2");
            session_3 = rs.getString("session_3");

            loadCombo1(rs.getString("group"));
            loadCombo2(rs.getString("session_1"));
            loadCombo3(rs.getString("session_2"));
            loadCombo4(rs.getString("session_3"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCombo1(String item) {
        try {
            String qry = "SELECT distinct groupNo FROM sessions";
            ResultSet rs = DBConnect.search(qry);
            jComboBox2.removeAllItems();
            jComboBox2.addItem(item);
            jComboBox2.addItem("Select...");
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("groupNo"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCombo2(String item) {
        try {
            String qry = "SELECT * FROM sessions where groupNo = '" + jComboBox2.getSelectedItem().toString() + "'";
            ResultSet rs = DBConnect.search(qry);
            jComboBox3.removeAllItems();
            jComboBox3.addItem(item);
            jComboBox3.addItem("Select...");
            while (rs.next()) {
                String subName = rs.getString("subName");
                String subCode = rs.getString("subCode");
                String tag = rs.getString("tag");

                jComboBox3.addItem(subName.concat("(").concat(subCode).concat(")").concat(" - ").concat(tag));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCombo3(String item) {
        try {
            String qry = "SELECT * FROM sessions where groupNo = '" + jComboBox2.getSelectedItem().toString() + "'";
            ResultSet rs = DBConnect.search(qry);
            jComboBox4.removeAllItems();
            jComboBox4.addItem(item);
            jComboBox4.addItem("Select...");
            while (rs.next()) {
                String subName = rs.getString("subName");
                String subCode = rs.getString("subCode");
                String tag = rs.getString("tag");

                jComboBox4.addItem(subName.concat("(").concat(subCode).concat(")").concat(" - ").concat(tag));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCombo4(String item) {
        try {
            String qry = "SELECT * FROM sessions where groupNo = '" + jComboBox2.getSelectedItem().toString() + "'";
            ResultSet rs = DBConnect.search(qry);
            jComboBox1.removeAllItems();
            jComboBox1.addItem(item);
            jComboBox1.addItem("Select...");
            while (rs.next()) {
                String subName = rs.getString("subName");
                String subCode = rs.getString("subCode");
                String tag = rs.getString("tag");

                jComboBox1.addItem(subName.concat("(").concat(subCode).concat(")").concat(" - ").concat(tag));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
