/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import service.DBConnect;

/**
 *
 * @author User
 */
public class locAllo_sessions extends javax.swing.JPanel {

    Generator generator;
    ResultSet rs = null;
    String ID = null;
    String building, session, tag;
    /**
     * Creates new form locAllo_sessions
     */
    public locAllo_sessions() {
        initComponents();
        
        LoadSessionBuilding();
        sessionRoomTableLoad();
        consecutiveSessionLoad();
        
    }
    
    public void sessionRoomTableLoad(){
        try{
            String query = "SELECT  building, room, tagged_session FROM tagged_sessions";
            //pst = con.prepareStatement(query);
            rs = DBConnect.search(query);
            
            roomReservSessionTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void consecutiveSessionLoad(){
        try{
            String sql = "SELECT * FROM consecutive_sessions";
            //pst = con.prepareStatement(sql);
            rs = DBConnect.search(sql);
            
            consecutiveSessionTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void clearSessionRoom(){
        sessionSelect.setSelectedItem("Select a Session");
        selectBuildSession.setSelectedItem("Select a Building");
        selectRoomSession.setSelectedItem("Select a Room");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locAllo_sessions = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        roomReservSessionTable = new javax.swing.JTable();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        sessionSelect = new javax.swing.JComboBox<>();
        jLabel137 = new javax.swing.JLabel();
        selectBuildSession = new javax.swing.JComboBox<>();
        jLabel138 = new javax.swing.JLabel();
        selectRoomSession = new javax.swing.JComboBox<>();
        sessionReservBtn = new javax.swing.JButton();
        sessionDel = new javax.swing.JButton();
        jPanel43 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        consecutiveSessionTable = new javax.swing.JTable();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        conSessBox = new javax.swing.JComboBox<>();
        jLabel141 = new javax.swing.JLabel();
        specifySamesesRoom = new javax.swing.JComboBox<>();
        jButton22 = new javax.swing.JButton();
        conSesDel = new javax.swing.JButton();

        locAllo_sessions.setBackground(new java.awt.Color(0, 204, 204));

        jLabel134.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel134.setText("Location Allocation for Sessions");

        jPanel42.setBackground(new java.awt.Color(102, 102, 102));

        roomReservSessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        roomReservSessionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomReservSessionTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(roomReservSessionTable);

        jLabel135.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(255, 255, 255));
        jLabel135.setText("Room Reservations for sessions");

        jLabel136.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(255, 255, 255));
        jLabel136.setText("Session");

        sessionSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sessionSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sessionSelectItemStateChanged(evt);
            }
        });

        jLabel137.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(255, 255, 255));
        jLabel137.setText("Building");

        selectBuildSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectBuildSession.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectBuildSessionItemStateChanged(evt);
            }
        });

        jLabel138.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 255, 255));
        jLabel138.setText("Room");

        selectRoomSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sessionReservBtn.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        sessionReservBtn.setText("Reserve Room");
        sessionReservBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionReservBtnActionPerformed(evt);
            }
        });

        sessionDel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        sessionDel.setText("DELETE");
        sessionDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel136)
                            .addComponent(jLabel137)
                            .addComponent(jLabel138))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sessionSelect, 0, 306, Short.MAX_VALUE)
                            .addComponent(selectBuildSession, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectRoomSession, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sessionReservBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessionDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(jLabel135)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel136)
                            .addComponent(sessionSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel137)
                            .addComponent(selectBuildSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel138)
                            .addComponent(selectRoomSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(sessionReservBtn))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(sessionDel)
                .addGap(27, 27, 27))
        );

        jPanel43.setBackground(new java.awt.Color(0, 102, 153));

        consecutiveSessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consecutiveSessionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consecutiveSessionTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(consecutiveSessionTable);

        jLabel139.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setText("Specify Concecitive Sessions");

        jLabel140.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 255, 255));
        jLabel140.setText("Concecitive Session");

        conSessBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Session" }));

        jLabel141.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 255, 255));
        jLabel141.setText("Specify Same Room");

        specifySamesesRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Option", "Yes", "No" }));

        jButton22.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton22.setText("Specify");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        conSesDel.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        conSesDel.setText("DELETE");

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(conSesDel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel43Layout.createSequentialGroup()
                                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel43Layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel43Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel140)
                                            .addComponent(jLabel141))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(conSessBox, 0, 245, Short.MAX_VALUE)
                                            .addComponent(specifySamesesRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel139)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel140)
                            .addComponent(conSessBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel141)
                            .addComponent(specifySamesesRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton22))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(conSesDel)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout locAllo_sessionsLayout = new javax.swing.GroupLayout(locAllo_sessions);
        locAllo_sessions.setLayout(locAllo_sessionsLayout);
        locAllo_sessionsLayout.setHorizontalGroup(
            locAllo_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locAllo_sessionsLayout.createSequentialGroup()
                .addGroup(locAllo_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locAllo_sessionsLayout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addComponent(jLabel134))
                    .addGroup(locAllo_sessionsLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(locAllo_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(6739, Short.MAX_VALUE))
        );
        locAllo_sessionsLayout.setVerticalGroup(
            locAllo_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locAllo_sessionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel134)
                .addGap(18, 18, 18)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(locAllo_sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(locAllo_sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roomReservSessionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomReservSessionTableMouseClicked

        int row = roomReservSessionTable.getSelectedRow();

        ID = roomReservSessionTable.getValueAt(row, 2).toString();

    }//GEN-LAST:event_roomReservSessionTableMouseClicked

    private void sessionSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sessionSelectItemStateChanged

        if(evt.getStateChange() == ItemEvent.SELECTED){
            session = sessionSelect.getSelectedItem().toString();
            selectRoomSession.removeAllItems();
            LoadSessionRoom();

        }
    }//GEN-LAST:event_sessionSelectItemStateChanged

    private void selectBuildSessionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectBuildSessionItemStateChanged

        if(evt.getStateChange() == ItemEvent.SELECTED){
            building = selectBuildSession.getSelectedItem().toString();
            selectRoomSession.removeAllItems();
            LoadSessionRoom();

        }
    }//GEN-LAST:event_selectBuildSessionItemStateChanged

    private void sessionReservBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionReservBtnActionPerformed

        String session = sessionSelect.getSelectedItem().toString();
        String building = selectBuildSession.getSelectedItem().toString();
        String room = selectRoomSession.getSelectedItem().toString();
        String taggedSession = session + "\n" + room;

        if(session.equals("Select a Session") || building.equals("Select a Building") || room.equals("Select a Room")){
            JOptionPane.showMessageDialog(null, "Please Select All The Related Information");
        }else{
            try{

                String q = "INSERT INTO tagged_sessions (session,building, room, tagged_session) VALUES ( '"+ session +"','" + building + "', '"+ room +"', '"+ taggedSession +"')";
                DBConnect.iud(q);
                //pst = con.prepareStatement(q);
                //pst.execute();

                JOptionPane.showMessageDialog(null, "Data Successfully Added!");

                sessionRoomTableLoad();

            }catch(Exception e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_sessionReservBtnActionPerformed

    private void sessionDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionDelActionPerformed

        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete");

        if(x == 0){

            try{
                String query = "DELETE from tagged_sessions where tagged_session = '"+ ID +"'";
                DBConnect.iud(query);
                //pst = con.prepareStatement(query);
                //pst.execute();

                sessionRoomTableLoad();

            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_sessionDelActionPerformed

    private void consecutiveSessionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consecutiveSessionTableMouseClicked

        int row = consecutiveSessionTable.getSelectedRow();

        ID = consecutiveSessionTable.getValueAt(row, 0).toString();
        String group = consecutiveSessionTable.getValueAt(row, 1).toString();
        String session1 = consecutiveSessionTable.getValueAt(row, 2).toString();
        String session2 = consecutiveSessionTable.getValueAt(row, 3).toString();
        String session3 = consecutiveSessionTable.getValueAt(row, 4).toString();

        conSessBox.setSelectedItem(ID);

    }//GEN-LAST:event_consecutiveSessionTableMouseClicked

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

        String consecutiveSesID = conSessBox.getSelectedItem().toString();
        String specify = specifySamesesRoom.getSelectedItem().toString();

        if(consecutiveSesID.equals("Select a Session") || building.equals("Select a Option")){
            JOptionPane.showMessageDialog(null, "Please Select All The Related Information");
        }else{
            try{

                String q = "INSERT INTO consecutiveroom (consecutive_session_id, specify_sameRoom) VALUES ('"+ consecutiveSesID +"', '"+ specify +"')";
                DBConnect.iud(q);
                //pst = con.prepareStatement(q);
                //pst.execute();

                JOptionPane.showMessageDialog(null, "Data Successfully Added!");

                clearSessionRoom();

            }catch(Exception e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton22ActionPerformed

    
    private void LoadSessionRoom(){
        try{
            String s1 = "SELECT tag FROM sessions where sessions = '"+ session +"'";
            ResultSet rs1 = DBConnect.search(s1);
            rs1.next();
            tag = rs1.getString("tag");
            
            
            String q = "SELECT room FROM tagged_rooms where building = '"+ building +"' and tag = '"+ tag +"'";
            ResultSet rs = DBConnect.search(q);
            selectRoomSession.removeAllItems();
            selectRoomSession.addItem("Select a Room");
            
            while(rs.next()){
                selectRoomSession.addItem(rs.getString("room"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void LoadSessions(){
        try{
            String q = "SELECT sessions FROM sessions";
            ResultSet rs = DBConnect.search(q);
            sessionSelect.removeAllItems();
            sessionSelect.addItem("Select a Session");
            
            while(rs.next()){
                sessionSelect.addItem(rs.getString("sessions"));
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void LoadSessionBuilding(){
        try{
            String sql = "SELECT Name FROM building";
            ResultSet rs = DBConnect.search(sql);
            selectBuildSession.removeAllItems();
            selectBuildSession.addItem("Select a Building");
            
            while(rs.next()){
                selectBuildSession.addItem(rs.getString("Name"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
            
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conSesDel;
    private javax.swing.JComboBox<String> conSessBox;
    private javax.swing.JTable consecutiveSessionTable;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel locAllo_sessions;
    private javax.swing.JTable roomReservSessionTable;
    private javax.swing.JComboBox<String> selectBuildSession;
    private javax.swing.JComboBox<String> selectRoomSession;
    private javax.swing.JButton sessionDel;
    private javax.swing.JButton sessionReservBtn;
    private javax.swing.JComboBox<String> sessionSelect;
    private javax.swing.JComboBox<String> specifySamesesRoom;
    // End of variables declaration//GEN-END:variables
}
