/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import service.DBConnect;

/**
 *
 * @author User
 */
public class locAllo_groups extends javax.swing.JPanel {

    /**
     * Creates new form locAllo_groups
     */
    public locAllo_groups() {
        initComponents();
        
        LoadBuildings();
        LoadLecturers();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locAllo_groups = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        locAlloLecSelect = new javax.swing.JComboBox<>();
        jLabel129 = new javax.swing.JLabel();
        locAlloBuildSelect = new javax.swing.JComboBox<>();
        jLabel130 = new javax.swing.JLabel();
        locAlloRoomSelect = new javax.swing.JComboBox<>();
        alloLecBtn = new javax.swing.JButton();
        jPanel41 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        locAlloGroupSelect = new javax.swing.JComboBox<>();
        jLabel132 = new javax.swing.JLabel();
        locAlloGroupBuildSelect = new javax.swing.JComboBox<>();
        jLabel133 = new javax.swing.JLabel();
        locAlloGroupRoomSelect = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jLabel145 = new javax.swing.JLabel();
        groupOption = new javax.swing.JComboBox<>();

        locAllo_groups.setBackground(new java.awt.Color(0, 204, 204));

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel125.setText("Location Allocation for groups and Lecturers");

        jPanel40.setBackground(new java.awt.Color(102, 102, 102));

        jLabel126.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(255, 255, 255));
        jLabel126.setText("Lecturer Location Allocation");

        jLabel128.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel128.setText("Lecturer Name");

        locAlloLecSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        locAlloLecSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locAlloLecSelectActionPerformed(evt);
            }
        });

        jLabel129.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel129.setText("Building");

        locAlloBuildSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        locAlloBuildSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                locAlloBuildSelectItemStateChanged(evt);
            }
        });

        jLabel130.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel130.setText("Room");

        locAlloRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        alloLecBtn.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        alloLecBtn.setText("Add Lecturer Location");
        alloLecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alloLecBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel126)
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alloLecBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel128)
                            .addComponent(jLabel129)
                            .addComponent(jLabel130))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locAlloLecSelect, 0, 321, Short.MAX_VALUE)
                            .addComponent(locAlloBuildSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(locAlloRoomSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel126)
                .addGap(65, 65, 65)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel128)
                    .addComponent(locAlloLecSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel129)
                    .addComponent(locAlloBuildSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel130)
                    .addComponent(locAlloRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(alloLecBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel41.setBackground(new java.awt.Color(0, 102, 153));

        jLabel127.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setText("Groups Location Allocation");

        jLabel131.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel131.setText("Group/Sub Group");

        locAlloGroupSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        locAlloGroupSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                locAlloGroupSelectItemStateChanged(evt);
            }
        });

        jLabel132.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel132.setText("Building");

        locAlloGroupBuildSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        locAlloGroupBuildSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                locAlloGroupBuildSelectItemStateChanged(evt);
            }
        });

        jLabel133.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel133.setText("Room");

        locAlloGroupRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton16.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton16.setText("Add Group Location");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel145.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel145.setText("Option");

        groupOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Option", "Group", "SubGroup", " " }));
        groupOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupOptionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel127)
                .addGap(193, 193, 193))
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel131)
                            .addComponent(jLabel132)
                            .addComponent(jLabel133)
                            .addComponent(jLabel145))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locAlloGroupSelect, 0, 338, Short.MAX_VALUE)
                            .addComponent(locAlloGroupBuildSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(locAlloGroupRoomSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(groupOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel127)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel145)
                    .addComponent(groupOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locAlloGroupSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel131))
                .addGap(35, 35, 35)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locAlloGroupBuildSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel132))
                .addGap(33, 33, 33)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locAlloGroupRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel133))
                .addGap(57, 57, 57)
                .addComponent(jButton16)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout locAllo_groupsLayout = new javax.swing.GroupLayout(locAllo_groups);
        locAllo_groups.setLayout(locAllo_groupsLayout);
        locAllo_groupsLayout.setHorizontalGroup(
            locAllo_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locAllo_groupsLayout.createSequentialGroup()
                .addGroup(locAllo_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locAllo_groupsLayout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel125))
                    .addGroup(locAllo_groupsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(6688, Short.MAX_VALUE))
        );
        locAllo_groupsLayout.setVerticalGroup(
            locAllo_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locAllo_groupsLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel125)
                .addGap(57, 57, 57)
                .addGroup(locAllo_groupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(locAllo_groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(locAllo_groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locAlloLecSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locAlloLecSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locAlloLecSelectActionPerformed

    private void locAlloBuildSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_locAlloBuildSelectItemStateChanged

        if(evt.getStateChange() == ItemEvent.SELECTED){
            building = locAlloBuildSelect.getSelectedItem().toString();
            locAlloRoomSelect.removeAllItems();
            LoadLecAllocationRoom();
        }

    }//GEN-LAST:event_locAlloBuildSelectItemStateChanged

    private void alloLecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alloLecBtnActionPerformed

        String lec = locAlloLecSelect.getSelectedItem().toString();
        String build = locAlloBuildSelect.getSelectedItem().toString();
        String room = locAlloRoomSelect.getSelectedItem().toString();

        String lecturer;

        if(lec.equals("Select a Lecturer") || build.equals("Select a Building") || room.equals("Select a Room")){
            JOptionPane.showMessageDialog(null, "Please Select All The Related Information");
        }else{
            try{

                String q = "INSERT INTO lec_room (lec_Name,building, room) VALUES ( '"+ lec +"','" + build + "', '"+ room +"')";
                DBConnect.iud(q);
                //pst = con.prepareStatement(q);
                //pst.execute();

                JOptionPane.showMessageDialog(null, "Data Successfully Added!");
                /* String q = "SELECT lec_Name,room From lec_room where room = '"+ room +"'";
                pst = con.prepareStatement(q);
                ResultSet r1 = pst.executeQuery();
                boolean valid = r1.next();

                if(valid == true){
                    lecturer = r1.getString("lec_Name");

                }
                */
                clearLecRooms();

            }catch(Exception e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_alloLecBtnActionPerformed

    private void locAlloGroupSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_locAlloGroupSelectItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_locAlloGroupSelectItemStateChanged

    private void locAlloGroupBuildSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_locAlloGroupBuildSelectItemStateChanged

        if(evt.getStateChange() == ItemEvent.SELECTED){
            building2 = locAlloGroupBuildSelect.getSelectedItem().toString();
            locAlloGroupRoomSelect.removeAllItems();
            LoadGroupRoom();

        }
    }//GEN-LAST:event_locAlloGroupBuildSelectItemStateChanged

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        String group = locAlloGroupSelect.getSelectedItem().toString();
        String build = locAlloGroupBuildSelect.getSelectedItem().toString();
        String room = locAlloGroupRoomSelect.getSelectedItem().toString();

        if(group.equals("Select a group") || build.equals("Select a Building") || room.equals("Select a Room") || group.equals("Select a SubGroup")){
            JOptionPane.showMessageDialog(null, "Please Select All The Related Information");
        }else{
            try{

                String q = "INSERT INTO group_room (groups,building, room) VALUES ( '"+ group +"','" + build + "', '"+ room +"')";
                DBConnect.iud(q);
                //pst = con.prepareStatement(q);
                //pst.execute();

                JOptionPane.showMessageDialog(null, "Data Successfully Added!");

                clearGroupRoom();

            }catch(Exception e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton16ActionPerformed

    private void groupOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupOptionItemStateChanged

        if(evt.getStateChange() == ItemEvent.SELECTED){
            option = groupOption.getSelectedItem().toString();
            locAlloGroupSelect.removeAllItems();
            loadGroups();

        }

    }//GEN-LAST:event_groupOptionItemStateChanged

    String building,building2 ,option;
    private void clearLecRooms(){
        locAlloLecSelect.setSelectedItem("Select a Lecturer");
        locAlloBuildSelect.setSelectedItem("Select a Building");
        locAlloRoomSelect.setSelectedItem("Select a Room");
        
    }
    
    private void clearGroupRoom(){
        groupOption.setSelectedItem("Select a Option");
        locAlloGroupSelect.setSelectedItem("Select a group");
        locAlloGroupBuildSelect.setSelectedItem("Select a Building");
        locAlloGroupRoomSelect.setSelectedItem("Select a Room");
    }
    
    private void LoadLecAllocationRoom(){
        try{
            String q = "SELECT room FROM location where buildingName = '"+ building +"' ";
            ResultSet rs = DBConnect.search(q);
            locAlloRoomSelect.removeAllItems();
            locAlloRoomSelect.addItem("Select a Room");
            
            while(rs.next()){
                locAlloRoomSelect.addItem(rs.getString("room"));
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    private void LoadBuildings(){
        try{
            String sql = "SELECT Name FROM building";
            ResultSet rs = DBConnect.search(sql);
            locAlloBuildSelect.removeAllItems();
            locAlloBuildSelect.addItem("Select a Building");
            
            locAlloGroupBuildSelect.removeAllItems();
            locAlloGroupBuildSelect.addItem("Select a Building");
            
            while(rs.next()){
                
                locAlloBuildSelect.addItem(rs.getString("Name"));
                
                locAlloGroupBuildSelect.addItem(rs.getString("Name"));
            }
            
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void loadGroups(){
        try{
            
            if(option.equals("Group")){
               
                String q = "SELECT batch FROM groups";
                ResultSet rs = DBConnect.search(q);
                locAlloGroupSelect.removeAllItems();
                locAlloGroupSelect.addItem("Select a group");
                      
                while(rs.next()){
                    locAlloGroupSelect.addItem(rs.getString("batch"));
                
                }
            }else if(option.equals("SubGroup")){
                
                String q1 = "SELECT group FROM subgroup";
                ResultSet rs1 = DBConnect.search(q1);
                locAlloGroupSelect.removeAllItems();
                locAlloGroupSelect.addItem("Select a sub group");
                
                while(rs1.next()){
                    locAlloGroupSelect.addItem(rs1.getString("group"));
                
                }
            }
            
            
            
        }catch(Exception e){
           e.printStackTrace();
        }
    }
    
    private void LoadGroupRoom(){
        try{
           String q = "SELECT room FROM location where buildingName = '"+ building2 +"' ";
            ResultSet rs = DBConnect.search(q);
            locAlloGroupRoomSelect.removeAllItems();
            locAlloGroupRoomSelect.addItem("Select a Room");
            
            while(rs.next()){
                locAlloGroupRoomSelect.addItem(rs.getString("room"));
            } 
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void LoadLecturers(){
        try{
            
            String q = "SELECT name FROM lec";
            ResultSet rs = DBConnect.search(q);
            locAlloLecSelect.removeAllItems();
            locAlloLecSelect.addItem("Select a Lecturer");
            
            while(rs.next()){
                locAlloLecSelect.addItem(rs.getString("name"));
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alloLecBtn;
    private javax.swing.JComboBox<String> groupOption;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JComboBox<String> locAlloBuildSelect;
    private javax.swing.JComboBox<String> locAlloGroupBuildSelect;
    private javax.swing.JComboBox<String> locAlloGroupRoomSelect;
    private javax.swing.JComboBox<String> locAlloGroupSelect;
    private javax.swing.JComboBox<String> locAlloLecSelect;
    private javax.swing.JComboBox<String> locAlloRoomSelect;
    private javax.swing.JPanel locAllo_groups;
    // End of variables declaration//GEN-END:variables
}
